#spring:
#  main:
#    banner-mode: "off"
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/courseScoreSchema.sql
#    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
#    username: root
#    password: test
#  jackson:
#    time-zone: GMT+2
#    date-format: dd-MM-yyyy HH:mm:ss
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml

